import { DifficultyPreset } from './types';

export const SVAERHEDSGRADER: Record<DifficultyPreset, Record<string, Record<string, any>>> = {
  let: {
    addition: { antalLed: 2, talMin: 1, talMax: 20, negativtal: false },
    subtraktion: { antalLed: 2, talMin: 1, talMax: 20, negativtal: false },
    multiplikation: { antalLed: 2, talMin: 1, talMax: 5, negativtal: false },
    division: { antalLed: 2, talMax: 20, decimaltal: false, negativtal: false },
    tabel: { talMax: 5, negativtal: false },
    procentDel: { talMin: 10, talMax: 100, decimaltal: false },
    procentSats: { talMin: 10, talMax: 100 },
    procentGrundtal: { talMin: 10, talMax: 100 },
    laengde: { enhederValgt: ['mm', 'cm', 'dm', 'm'], decimaltal: false },
    ligningEttrin: { talMin: 1, talMax: 10, decimaltal: false, negativtal: false },
    ligningTotrin: { talMin: 1, talMax: 10, decimaltal: false, negativtal: false },
    ligningXBegge: { talMin: 1, talMax: 8, decimaltal: false, negativtal: false },
    ligningBogstaver: { talMax: 6, decimaltal: false, negativtal: false },
    algebraReducer: { antalLed: 2, talMax: 5, negativtal: false },
    algebraIndsaet: { talMin: 1, talMax: 6, decimaltal: false, negativtal: false },
    algebraUdvid: { talMax: 5 },
  },
  mellem: {
    addition: { antalLed: 2, talMin: 1, talMax: 100, negativtal: false },
    subtraktion: { antalLed: 2, talMin: 1, talMax: 100, negativtal: false },
    multiplikation: { antalLed: 2, talMin: 1, talMax: 10, negativtal: false },
    division: { antalLed: 2, talMax: 100, decimaltal: false, negativtal: false },
    tabel: { talMax: 9, negativtal: false },
    procentDel: { talMin: 50, talMax: 500, decimaltal: false },
    procentSats: { talMin: 50, talMax: 500 },
    procentGrundtal: { talMin: 50, talMax: 500 },
    laengde: { enhederValgt: ['mm', 'cm', 'dm', 'm'], decimaltal: false },
    ligningEttrin: { talMin: 1, talMax: 20, decimaltal: false, negativtal: false },
    ligningTotrin: { talMin: 1, talMax: 15, decimaltal: false, negativtal: false },
    ligningXBegge: { talMin: 1, talMax: 12, decimaltal: false, negativtal: false },
    ligningBogstaver: { talMax: 9, decimaltal: false, negativtal: false },
    algebraReducer: { antalLed: 3, talMax: 9, negativtal: true },
    algebraIndsaet: { talMin: 1, talMax: 12, decimaltal: false, negativtal: false },
    algebraUdvid: { talMax: 9 },
  },
  svaer: {
    addition: { antalLed: 4, talMin: 1, talMax: 200, negativtal: true },
    subtraktion: { antalLed: 4, talMin: 1, talMax: 200, negativtal: true },
    multiplikation: { antalLed: 3, talMin: 1, talMax: 12, negativtal: true },
    division: { antalLed: 3, talMax: 300, decimaltal: true, negativtal: true },
    tabel: { talMax: 12, negativtal: true },
    procentDel: { talMin: 100, talMax: 900, decimaltal: true },
    procentSats: { talMin: 100, talMax: 900 },
    procentGrundtal: { talMin: 100, talMax: 900 },
    laengde: { enhederValgt: ['mm', 'cm', 'dm', 'm'], decimaltal: true },
    ligningEttrin: { talMin: 1, talMax: 40, decimaltal: true, negativtal: true },
    ligningTotrin: { talMin: 1, talMax: 30, decimaltal: true, negativtal: true },
    ligningXBegge: { talMin: 1, talMax: 20, decimaltal: true, negativtal: true },
    ligningBogstaver: { talMax: 15, decimaltal: true, negativtal: true },
    algebraReducer: { antalLed: 4, talMax: 15, negativtal: true },
    algebraIndsaet: { talMin: 1, talMax: 20, decimaltal: true, negativtal: true },
    algebraUdvid: { talMax: 15 },
  },
};
