import { OpgavetypeDef, KategoriDef } from './types';
import {
  genererAdditionMult,
  genererSubtraktion,
  genererDivision,
  genererTabel,
  genererProcent,
  genererLaengde,
  genererLigningEttrin,
  genererLigningTotrin,
  genererLigningXBegge,
  genererLigningBogstaver,
  genererAlgebraReducer,
  genererAlgebraIndsaet,
  genererAlgebraUdvid,
} from './generators';

export const KATEGORIER: KategoriDef[] = [
  { id: 'regnearter', navn: 'Regnearter', icon: 'Calculator' },
  { id: 'procent', navn: 'Procent', icon: 'Percent' },
  { id: 'enheder', navn: 'Enheder', icon: 'Ruler' },
  { id: 'algebra', navn: 'Algebra & ligninger', icon: 'Sigma' },
];

export const OPGAVETYPER: OpgavetypeDef[] = [
  {
    id: 'addition',
    navn: 'Addition (+)',
    kategori: 'regnearter',
    eksempel: '8 + 5 + 3 = __',
    felter: ['antalLed', 'talMinMax', 'negativtal'],
    standard: { antalLed: 2, talMin: 1, talMax: 100, negativtal: false },
    generer: (rng, p) => genererAdditionMult(rng, '+', p),
  },
  {
    id: 'subtraktion',
    navn: 'Subtraktion (−)',
    kategori: 'regnearter',
    eksempel: '12 − 4 = __',
    felter: ['antalLed', 'talMinMax', 'negativtal'],
    standard: { antalLed: 2, talMin: 1, talMax: 100, negativtal: false },
    generer: (rng, p) => genererSubtraktion(rng, p),
  },
  {
    id: 'multiplikation',
    navn: 'Multiplikation (·)',
    kategori: 'regnearter',
    eksempel: '6 · 7 = __',
    felter: ['antalLed', 'talMinMax', 'negativtal'],
    standard: { antalLed: 2, talMin: 1, talMax: 12, negativtal: false },
    generer: (rng, p) => genererAdditionMult(rng, '·', p),
  },
  {
    id: 'division',
    navn: 'Division (:)',
    kategori: 'regnearter',
    eksempel: '36 : 6 = __',
    felter: ['antalLed', 'talMax', 'decimaltal', 'negativtal'],
    standard: { antalLed: 2, talMax: 100, decimaltal: false, negativtal: false },
    generer: (rng, p) => genererDivision(rng, p),
  },
  {
    id: 'tabel',
    navn: 'Multiplikationstabel',
    kategori: 'regnearter',
    eksempel: '3 · 5 = __',
    felter: ['talMax9', 'negativtal'],
    standard: { talMax: 9, negativtal: false },
    generer: (rng, p) => genererTabel(rng, p),
  },
  {
    id: 'procentDel',
    navn: 'Procent – find del',
    kategori: 'procent',
    eksempel: '56% af 700 = __',
    felter: ['talMinMax', 'decimaltal'],
    standard: { talMin: 50, talMax: 900, decimaltal: false },
    generer: (rng, p) => genererProcent(rng, 'del', p),
  },
  {
    id: 'procentSats',
    navn: 'Procent – find sats',
    kategori: 'procent',
    eksempel: '434 er __% af 700',
    felter: ['talMinMax'],
    standard: { talMin: 50, talMax: 900 },
    generer: (rng, p) => genererProcent(rng, 'sats', p),
  },
  {
    id: 'procentGrundtal',
    navn: 'Procent – find grundtal',
    kategori: 'procent',
    eksempel: '434 er 56% af __',
    felter: ['talMinMax'],
    standard: { talMin: 50, talMax: 900 },
    generer: (rng, p) => genererProcent(rng, 'grundtal', p),
  },
  {
    id: 'laengde',
    navn: 'Længdeomregning (mm/cm/dm/m)',
    kategori: 'enheder',
    eksempel: '4,7 cm = __ mm',
    felter: ['enheder', 'decimaltal'],
    standard: { enhederValgt: ['mm', 'cm', 'dm', 'm'], decimaltal: false },
    generer: (rng, p) => genererLaengde(rng, p),
  },
  {
    id: 'ligningEttrin',
    navn: 'Ligning – ettrins',
    kategori: 'algebra',
    eksempel: 'x + 5 = 12, x = __',
    felter: ['talMinMax', 'decimaltal', 'negativtal'],
    standard: { talMin: 1, talMax: 20, decimaltal: false, negativtal: false },
    generer: (rng, p) => genererLigningEttrin(rng, p),
  },
  {
    id: 'ligningTotrin',
    navn: 'Ligning – totrins',
    kategori: 'algebra',
    eksempel: '2x + 4 = 16, x = __',
    felter: ['talMinMax', 'decimaltal', 'negativtal'],
    standard: { talMin: 1, talMax: 20, decimaltal: false, negativtal: false },
    generer: (rng, p) => genererLigningTotrin(rng, p),
  },
  {
    id: 'ligningXBegge',
    navn: 'Ligning – x på begge sider',
    kategori: 'algebra',
    eksempel: '3x + 4 = x + 12, x = __',
    felter: ['talMinMax', 'decimaltal', 'negativtal'],
    standard: { talMin: 1, talMax: 15, decimaltal: false, negativtal: false },
    generer: (rng, p) => genererLigningXBegge(rng, p),
  },
  {
    id: 'ligningBogstaver',
    navn: 'Ligning med bogstaver (A og B)',
    kategori: 'algebra',
    eksempel: '3A + 5B = 2A + 10B, A = __B',
    felter: ['koefMax', 'decimaltal', 'negativtal'],
    standard: { talMax: 9, decimaltal: false, negativtal: false },
    generer: (rng, p) => genererLigningBogstaver(rng, p),
  },
  {
    id: 'algebraReducer',
    navn: 'Algebra – reducer udtryk',
    kategori: 'algebra',
    eksempel: '3x + 5x − 2x = __x',
    felter: ['antalLed', 'koefMax', 'negativtal'],
    standard: { antalLed: 3, talMax: 9, negativtal: false },
    generer: (rng, p) => genererAlgebraReducer(rng, p),
  },
  {
    id: 'algebraIndsaet',
    navn: 'Algebra – indsæt tal i udtryk',
    kategori: 'algebra',
    eksempel: 'Når x = 4: 2x + 3 = __',
    felter: ['talMinMax', 'decimaltal', 'negativtal'],
    standard: { talMin: 1, talMax: 12, decimaltal: false, negativtal: false },
    generer: (rng, p) => genererAlgebraIndsaet(rng, p),
  },
  {
    id: 'algebraUdvid',
    navn: 'Algebra – udvid parenteser',
    kategori: 'algebra',
    eksempel: '3(x + 2) = __',
    felter: ['koefMax'],
    standard: { talMax: 9 },
    generer: (rng, p) => genererAlgebraUdvid(rng, p),
  },
];

export const OPGAVETYPER_MAP = new Map<string, OpgavetypeDef>(
  OPGAVETYPER.map((t) => [t.id, t])
);
